name: scriletio
services:
  database:
    image: postgres:${POSTGRES_VERSION-16.2}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    image: sirtimme/scriletio:${SCRILETIO_VERSION-0.0.8}
    environment:
      OWNER_ID: ${OWNER_ID}
      TOKEN: ${TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      LOG_EXPORTER_ENDPOINT: ${LOG_EXPORTER_ENDPOINT}
    depends_on:
      - database

  adminer:
    image: adminer:${ADMINER_VERSION-4.8.1}
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  pg-data: