name: scriletio
services:
  database:
    image: postgres:${POSTGRES_VERSION-16.2}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: src/main/resources/docker/Dockerfile
    environment:
      OWNER_ID: ${OWNER_ID}
      TOKEN: ${TOKEN_DEV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      LOG_EXPORTER_ENDPOINT: ${LOG_EXPORTER_ENDPOINT}
    depends_on:
      - database

  adminer:
    image: adminer:${ADMINER_VERSION-4.8.1}
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      - database
    ports:
      - "8080:8080"

  collector:
    image: otel/opentelemetry-collector-contrib:0.104.0
    environment:
      LOKI_ENDPOINT: ${LOKI_ENDPOINT}
      OTLP_ENDPOINT: ${OTLP_ENDPOINT}
    volumes:
      - ./src/main/resources/open-telemetry/otel-config.yml:/otel-config.yml
    command: [ "--config=/otel-config.yml" ]
    ports:
      - "4317:4317"

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:3.1.0
    ports:
      - "3100:3100"

volumes:
  pg-data: