name: scriletio
services:
  database:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  bot:
    image: sirtimme/scriletio:${SCRILETIO_VERSION}
    environment:
      OWNER_ID: ${OWNER_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
    depends_on:
      - database

  adminer:
    image: adminer:${ADMINER_VERSION}
    depends_on:
      - database
    ports:
      - "${ADMINER_PORT}:8080"

volumes:
  pg-data: