name: scriletio
services:
  database:
    image: postgres:${POSTGRES_VERSION-16.2}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: ../../../../
      dockerfile: Dockerfile
    environment:
      OWNER_ID: ${OWNER_ID}
      TOKEN: ${TOKEN_DEV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_URL: ${POSTGRES_URL}
      LOG_EXPORTER_ENDPOINT: ${LOG_EXPORTER_ENDPOINT}
    depends_on:
      - database
    volumes:
      - ./../cfg/logback.xml:/home/gradle/src/cfg/logback.xml

  adminer:
    image: adminer:${ADMINER_VERSION-4.8.1}
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./../assets/adminer.css:/var/www/html/adminer.css

volumes:
  pg-data: