receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTLP_ENDPOINT}

exporters:
  otlphttp:
    endpoint: ${env:LOKI_ENDPOINT}
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp, debug ]