receivers:
  otlp:
    protocols:
      grpc:
        endpoint: collector:4317
exporters:
  otlphttp:
    endpoint: http://loki:3100/otlp
  logging:
    verbosity: detailed
service:
  pipelines:
    logs:
      receivers: [ otlp ]
      exporters: [ logging, otlphttp ]